# Generated by Django 5.2.3 on 2025-07-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='default@example.com', max_length=199, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('JURISTE', 'Jurist'), ('RH', 'Resources Humaines'), ('MANAGER', 'Manager'), ('SAFETY_MANAGER', 'Safety Manager'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', help_text='Defines the user role in the system', max_length=20, verbose_name='Role'),
        ),
    ]
