# Generated by Django 5.2.3 on 2025-06-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('', 'Select a role'), ('employee', 'Employee'), ('safety_manager', 'Safety Manager'), ('admin', 'Administrator')], default='employee', help_text='Defines if user is an employee, safety manager, or admin.', max_length=20),
        ),
    ]
