# Generated by Django 5.2.3 on 2025-06-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_options_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, help_text='Is two-factor authentication enabled for this account?', verbose_name='2FA Enabled'),
        ),
    ]
