# Generated by Django 5.2.3 on 2025-06-21 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_two_factor_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='two_factor_enabled',
        ),
    ]
