# Generated by Django 5.2.3 on 2025-06-11 16:13

import atmp_app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ATMPIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_of_incident', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('declared', 'Declared'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='declared', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(limit_choices_to={'role': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='provider_incidents', to=settings.AUTH_USER_MODEL)),
                ('safety_manager', models.ForeignKey(limit_choices_to={'role': 'safety_manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='safety_manager_incidents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ATMPDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='atmp_docs/%Y/%m/%d/', validators=[atmp_app.models.validate_file_extension])),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='atmp_app.atmpincident')),
            ],
        ),
    ]
