# Generated by Django 5.2.3 on 2025-07-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=50)),
                ('decision', models.CharField(blank=True, choices=[('CONTEST', 'Contest'), ('DO_NOT_CONTEST', 'Do Not Contest'), ('NEED_MORE_INFO', 'Need More Info'), ('REFER_TO_EXPERT', 'Refer To Expert')], max_length=50, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Audit',
                'verbose_name_plural': 'Audits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contentieux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('subject', models.JSONField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('EN_COURS', 'In Progress'), ('CLOTURE', 'Closed')], default='DRAFT', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contentieux',
                'verbose_name_plural': 'Contentieux',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('DAT', 'DAT'), ('CERTIFICAT_MEDICAL', 'Certificat Médical'), ('ARRET_TRAVAIL', 'Arrêt de Travail')], max_length=50)),
                ('original_name', models.CharField(max_length=255)),
                ('file', models.FileField(default='documents/default.pdf', upload_to='documents/%Y/%m/%d/')),
                ('mime_type', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DossierATMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_of_incident', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('A_ANALYSER', 'À Analyser'), ('ANALYSE_EN_COURS', 'Analyse en Cours'), ('CONTESTATION_RECOMMANDEE', 'Contestation Recommandée')], default='A_ANALYSER', max_length=50)),
                ('entreprise', models.JSONField()),
                ('salarie', models.JSONField()),
                ('accident', models.JSONField()),
                ('service_sante', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dossier AT/MP',
                'verbose_name_plural': 'Dossiers AT/MP',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JuridictionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juridiction', models.CharField(choices=[('TRIBUNAL_JUDICIAIRE', 'Tribunal Judiciaire'), ('COUR_APPEL', "Cour d'Appel"), ('COUR_CASSATION', 'Cour de Cassation')], max_length=50)),
                ('submitted_at', models.DateTimeField()),
                ('decision', models.CharField(blank=True, choices=[('FAVORABLE', 'Favorable'), ('DEFAVORABLE', 'Défavorable')], max_length=50, null=True)),
                ('decision_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Juridiction Step',
                'verbose_name_plural': 'Juridiction Steps',
            },
        ),
        migrations.CreateModel(
            name='Temoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('coordonnees', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Témoin',
                'verbose_name_plural': 'Témoins',
            },
        ),
        migrations.CreateModel(
            name='Tiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('assurance', models.CharField(blank=True, max_length=255, null=True)),
                ('immatriculation', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Tiers Impliqué',
                'verbose_name_plural': 'Tiers Impliqués',
            },
        ),
    ]
