# Generated by Django 5.2.3 on 2025-06-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atmp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmpincident',
            name='status',
            field=models.CharField(choices=[('', 'Select a choice'), ('declared', 'Declared'), ('in_progress', 'In Progress'), ('closed', 'Closed')], max_length=20),
        ),
    ]
