# Generated by Django 5.2.3 on 2025-07-19 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atmp_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiers',
            fields=[
                ('dossier_atmp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tiers_implique_record', serialize=False, to='atmp_app.dossieratmp')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('assurance', models.CharField(blank=True, max_length=255, null=True)),
                ('immatriculation', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Tiers Impliqué',
                'verbose_name_plural': 'Tiers Impliqués',
            },
        ),
        migrations.AlterField(
            model_name='contentieux',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('EN_COURS', 'EN_COURS'), ('CLOTURE', 'CLOTURE')], max_length=50),
        ),
        migrations.CreateModel(
            name='AuditChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.BooleanField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('document_required', models.BooleanField(default=False)),
                ('document_received', models.BooleanField(default=False)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='atmp_app.audit')),
            ],
            options={
                'verbose_name': 'Audit Checklist Item',
                'verbose_name_plural': 'Audit Checklist Items',
            },
        ),
        migrations.CreateModel(
            name='JuridictionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juridiction', models.CharField(choices=[('TRIBUNAL_JUDICIAIRE', 'TRIBUNAL_JUDICIAIRE'), ('COUR_APPEL', 'COUR_APPEL'), ('COUR_CASSATION', 'COUR_CASSATION')], max_length=50)),
                ('submitted_at', models.DateTimeField()),
                ('decision', models.CharField(blank=True, choices=[('FAVORABLE', 'FAVORABLE'), ('DEFAVORABLE', 'DEFAVORABLE')], max_length=50, null=True)),
                ('decision_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('contentieux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juridiction_steps_set', to='atmp_app.contentieux')),
            ],
            options={
                'verbose_name': 'Juridiction Step',
                'verbose_name_plural': 'Juridiction Steps',
            },
        ),
        migrations.CreateModel(
            name='Temoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('coordonnees', models.CharField(blank=True, max_length=255, null=True)),
                ('dossier_atmp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temoins_set', to='atmp_app.dossieratmp')),
            ],
            options={
                'verbose_name': 'Temoin',
                'verbose_name_plural': 'Temoins',
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('DAT', 'DAT'), ('CERTIFICAT_MEDICAL', 'CERTIFICAT_MEDICAL'), ('ARRET_TRAVAIL', 'ARRET_TRAVAIL'), ('TEMOIGNAGE', 'TEMOIGNAGE'), ('DECISION_CPAM', 'DECISION_CPAM'), ('EXPERTISE_MEDICALE', 'EXPERTISE_MEDICALE'), ('LETTRE_RESERVE', 'LETTRE_RESERVE'), ('CONTRAT_TRAVAIL', 'CONTRAT_TRAVAIL'), ('FICHE_POSTE', 'FICHE_POSTE'), ('RAPPORT_ENQUETE', 'RAPPORT_ENQUETE'), ('NOTIFICATION_TAUX', 'NOTIFICATION_TAUX'), ('COURRIER', 'COURRIER'), ('AUTRE', 'AUTRE')], max_length=50)),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('size', models.BigIntegerField()),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contentieux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_set', to='atmp_app.contentieux')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uploaded File',
                'verbose_name_plural': 'Uploaded Files',
            },
        ),
    ]
