# Generated by Django 5.2.3 on 2025-07-20 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atmp_app', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contentieux',
            name='actions',
            field=models.ManyToManyField(blank=True, related_name='contentieux_actions', to='atmp_app.action'),
        ),
        migrations.AddField(
            model_name='contentieux',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='contentieux_documents', to='atmp_app.document'),
        ),
        migrations.AddField(
            model_name='contentieux',
            name='juridiction_steps',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='dossieratmp',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='dossier_atmp_documents', to='atmp_app.document'),
        ),
        migrations.AddField(
            model_name='dossieratmp',
            name='temoins',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='dossieratmp',
            name='tiers_implique',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentieux',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('EN_COURS', 'En Cours'), ('CLOTURE', 'Clôturé')], default='DRAFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='contentieux',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_set', to='atmp_app.contentieux'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('DAT', 'DAT'), ('CERTIFICAT_MEDICAL', 'Certificat Médical'), ('ARRET_TRAVAIL', 'Arrêt de Travail'), ('TEMOIGNAGE', 'Témoignage'), ('DECISION_CPAM', 'Décision CPAM'), ('EXPERTISE_MEDICALE', 'Expertise Médicale'), ('LETTRE_RESERVE', 'Lettre de Réserve'), ('CONTRAT_TRAVAIL', 'Contrat de Travail'), ('FICHE_POSTE', 'Fiche de Poste'), ('RAPPORT_ENQUETE', 'Rapport d’Enquête'), ('NOTIFICATION_TAUX', 'Notification de Taux'), ('COURRIER', 'Courrier'), ('AUTRE', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dossieratmp',
            name='status',
            field=models.CharField(choices=[('A_ANALYSER', 'À Analyser'), ('ANALYSE_EN_COURS', 'Analyse en Cours'), ('CONTESTATION_RECOMMANDEE', 'Contestation Recommandée'), ('CLOTURE_SANS_SUITE', 'Clôture Sans Suite'), ('TRANSFORME_EN_CONTENTIEUX', 'Transformé en Contentieux')], default='A_ANALYSER', max_length=50),
        ),
        migrations.AlterField(
            model_name='juridictionstep',
            name='contentieux',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juridiction_steps_set', to='atmp_app.contentieux'),
        ),
        migrations.AlterField(
            model_name='temoin',
            name='dossier_atmp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temoin_set', to='atmp_app.dossieratmp'),
        ),
        migrations.CreateModel(
            name='AuditChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.BooleanField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('document_required', models.BooleanField(default=False)),
                ('document_received', models.BooleanField(default=False)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='atmp_app.audit')),
            ],
            options={
                'verbose_name': 'Audit Checklist Item',
                'verbose_name_plural': 'Audit Checklist Items',
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('DAT', 'DAT'), ('CERTIFICAT_MEDICAL', 'Certificat Médical'), ('ARRET_TRAVAIL', 'Arrêt de Travail'), ('TEMOIGNAGE', 'Témoignage'), ('DECISION_CPAM', 'Décision CPAM'), ('EXPERTISE_MEDICALE', 'Expertise Médicale'), ('LETTRE_RESERVE', 'Lettre de Réserve'), ('CONTRAT_TRAVAIL', 'Contrat de Travail'), ('FICHE_POSTE', 'Fiche de Poste'), ('RAPPORT_ENQUETE', 'Rapport d’Enquête'), ('NOTIFICATION_TAUX', 'Notification de Taux'), ('COURRIER', 'Courrier'), ('AUTRE', 'Autre')], max_length=50)),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('size', models.BigIntegerField()),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contentieux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_set', to='atmp_app.contentieux')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uploaded File',
                'verbose_name_plural': 'Uploaded Files',
            },
        ),
    ]
