# Generated by Django 5.2.3 on 2025-07-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atmp_app', '0003_contentieux_actions_contentieux_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
