# Generated by Django 5.2.3 on 2025-07-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atmp_app', '0004_document_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
